name: AVA

on:
  push:
  pull_request:

env:
  FORCE_COLOR: true

jobs:
  test:
    name: Node ${{ matrix.node_version}}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node_version: [16]
        os: [ubuntu-latest]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Use Node ${{ matrix.node_version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node_version }}
    - name: Restore Cache
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ matrix.os }}-${{ matrix.node_version}}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ matrix.os }}-${{ matrix.node_version }}-yarn-
    - name: Install Yarn Dependencies
      run: yarn install
    - name: Test Coverage
      run: yarn coverage
